# Generated by Django 3.2.4 on 2021-11-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='symptom_disease',
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_symtpom',
            field=models.ManyToManyField(blank=True, to='predict.Symptom'),
        ),
    ]
