# Generated by Django 3.2.4 on 2021-11-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20211126_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='disease_symtpom',
            new_name='disease_symptom',
        ),
    ]
