# Generated by Django 3.2.4 on 2021-11-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20211126_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='prevention',
            field=models.TextField(default=''),
        ),
    ]
